# Generated by Django 5.1.3 on 2024-12-06 22:24

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    # Get the model classes (using apps.get_model() to ensure compatibility across migrations)
    List = apps.get_model("webapp", "List")

    List.objects.create(name="chores")
    List.objects.create(name="groceries")


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_item_created_list_created_list_last_updated"),
    ]

    operations = [
        migrations.RunPython(
            populate_initial_data
        ),  # This will run the populate function
    ]
