# Generated by Django 5.1.3 on 2024-12-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_meal_user_item_recurring_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
